spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness
      database: airecommendationfitness

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: activity-processor-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"


kafka:
  topic:
    name: activity-events

gemini:
  api:
    key: ${GEMINI_API_KEY}
    base-url: https://generativelanguage.googleapis.com
    model: gemini-3.7-flash

server:
  port: 8083


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: aiservice:8083